[all:vars]
ansible_user=enz
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[kube_control_plane]
master01 ansible_host=35.247.176.106 ip=10.148.0.6 access_ip=10.148.0.6
master02 ansible_host=34.21.157.112 ip=10.148.0.7 access_ip=10.148.0.7
master03 ansible_host=35.197.144.202 ip=10.148.0.8 access_ip=10.148.0.8

[etcd:children]
kube_control_plane

[kube_node]
worker01 ansible_host=34.40.154.60 ip=10.152.0.2 access_ip=10.152.0.2
worker02 ansible_host=34.87.245.69 ip=10.152.0.3 access_ip=10.152.0.3
